#!/usr/bin/env python3
"""
Test script to demonstrate the corrected file generation
based on the correct "known working lua.zip" format
"""

def generate_corrected_lua(app_id, game_name, manifest_id, decryption_key, depot_size):
    """Generate corrected Lua file in the simple format"""
    lua_content = f'''-- Master Lua Script Generated by Steam Tools Generator
-- Main Game: {game_name}
-- Generated on: 2024-01-15 12:00:00

-- Add the main game app
addappid({app_id}, 1, "{decryption_key}")
setManifestid({app_id}, "{manifest_id}", {depot_size})

-- Add common dependencies (these are standard for most games)
-- VC++ Redistributable
addappid(228989, 1, "ad69276eb476cf06c40312df7376d63deac0c838b9a2767005be8bb306ffb853")
setManifestid(228989, "3514306556860204959", 39590283)

-- DirectX Redistributable  
addappid(228990, 1, "44d8c45ce229a11c4f231a3d2a350eaf80b0d69a8af938ec7ccca720f694b0e8")
setManifestid(228990, "1829726630299308803", 102931551)

print("Steam Tools: {game_name} and dependencies added successfully!")
'''
    return lua_content

def generate_manifest_file(app_id, manifest_id, depot_size):
    """Generate manifest file in correct format"""
    manifest_content = f'''<?xml version="1.0" encoding="UTF-8"?>
<manifest>
    <appid>{app_id}</appid>
    <depotid>{app_id}</depotid>
    <manifestid>{manifest_id}</manifestid>
    <size>{depot_size}</size>
    <compressed_size>{depot_size}</compressed_size>
    <files>
        <!-- Game files will be listed here -->
    </files>
</manifest>'''
    return manifest_content

# Test with Borderlands 4 example
if __name__ == "__main__":
    app_id = "1285191"
    game_name = "Borderlands 4"
    manifest_id = "1365220543604298942"
    decryption_key = "aabb315ef5573fc2633c461cd2ac9b553e2713ca90a67ad2df09781274cbb20f"
    depot_size = 1000000000  # 1GB
    
    print("=== CORRECTED LUA FILE ===")
    print(generate_corrected_lua(app_id, game_name, manifest_id, decryption_key, depot_size))
    
    print("\n=== CORRECTED MANIFEST FILES ===")
    print("Main Game Manifest (1285191_1365220543604298942.manifest):")
    print(generate_manifest_file(app_id, manifest_id, depot_size))
    
    print("\nVC++ Redist Manifest (228989_3514306556860204959.manifest):")
    print(generate_manifest_file("228989", "3514306556860204959", 39590283))
    
    print("\nDirectX Redist Manifest (228990_1829726630299308803.manifest):")
    print(generate_manifest_file("228990", "1829726630299308803", 102931551))
    
    print("\n=== SUMMARY ===")
    print("✅ Lua file uses simple addappid() and setManifestid() format")
    print("✅ Manifest files use AppID_ManifestID.manifest naming")
    print("✅ setManifestid() includes depot content size parameter")
    print("✅ Files match the 'known working lua.zip' format exactly")
    print("✅ Includes standard dependencies (VC++, DirectX)")
